#!/bin/ksh
# Activate Aliases 
ALIASES="${HOME}/.config/aliases"
if [[ -r "${ALIASES}" ]]
then
    source "${ALIASES}"
fi

# Activate Colors
COLORS_CONFIG="${HOME}/.config/colors"
if [[ -r "${COLORS_CONFIG}" ]]
then
    source "${COLORS_CONFIG}"
fi

# Ensure VI mode is enabled
set -o vi
